<?php

declare(strict_types=1);

namespace HalfBaked\Baking;

use HalfBaked\Ollama\OllamaClient;
use HalfBaked\Pipeline\Step;

/**
 * The Baker: turns LLM pipeline steps into deterministic PHP code.
 *
 * Analyzes execution logs (input/output pairs) to infer the
 * transformation pattern, then generates a PHP class that
 * implements BakedStepInterface with the same behavior.
 *
 * The generated code replaces the LLM call entirely — zero
 * inference cost, deterministic results, version-controllable.
 */
class Baker
{
    public function __construct(
        private OllamaClient $ollama,
        private ?OllamaClient $reasoningModel = null,
    ) {}

    /**
     * Bake a step into a PHP class.
     *
     * @param Step    $step      The step definition
     * @param array[] $logs      Execution logs (input/output pairs)
     * @param string  $outputDir Directory to write the generated class
     * @param string  $namespace PHP namespace for the class
     * @return array{success: bool, file: string, class: string, message: string}
     */
    public function bake(Step $step, array $logs, string $outputDir, string $namespace): array
    {
        $className = $this->generateClassName($step->getName());
        $fqcn = $namespace . '\\' . $className;

        // Build the baking prompt with all execution examples
        $prompt = $this->buildBakingPrompt($step, $logs, $className, $namespace);

        // Use reasoning model if available, otherwise the pipeline's ollama
        $client = $this->reasoningModel ?? $this->ollama;
        $model = $this->reasoningModel ? 'qwen3:32b' : ($step->getModel() ?? 'llama3.2');

        try {
            $result = $client->generate(
                model: $model,
                prompt: $prompt,
                system: $this->bakingSystemPrompt(),
                schema: [
                    'php_code' => 'string',
                    'explanation' => 'string',
                    'confidence' => [
                        'type' => 'number',
                        'description' => 'Confidence score 0.0-1.0 that this code correctly replaces the LLM',
                    ],
                ],
                temperature: 0.1,
            );
        } catch (\Throwable $e) {
            return [
                'success' => false,
                'file' => '',
                'class' => '',
                'message' => 'LLM failed to generate baked code: ' . $e->getMessage(),
            ];
        }

        $phpCode = $result['php_code'] ?? '';
        $confidence = (float) ($result['confidence'] ?? 0);
        $explanation = $result['explanation'] ?? '';

        if (empty($phpCode)) {
            return [
                'success' => false,
                'file' => '',
                'class' => '',
                'message' => 'LLM returned empty code',
            ];
        }

        // Strip ```php fences if the model wrapped them
        $phpCode = $this->stripCodeFences($phpCode);

        // Validate: must contain class definition and execute method
        if (!str_contains($phpCode, "class {$className}") || !str_contains($phpCode, 'function execute')) {
            return [
                'success' => false,
                'file' => '',
                'class' => '',
                'message' => "Generated code doesn't contain expected class '{$className}' or execute() method",
            ];
        }

        // Write the file
        if (!is_dir($outputDir)) {
            mkdir($outputDir, 0755, true);
        }

        $filePath = $outputDir . '/' . $className . '.php';
        $header = "<?php\n\n"
            . "declare(strict_types=1);\n\n"
            . "// Auto-generated by HalfBaked Baker\n"
            . "// Baked from {$step->getName()} step ({$this->countRuns($logs)} execution logs)\n"
            . "// Confidence: " . round($confidence * 100) . "%\n"
            . "// " . str_replace("\n", "\n// ", $explanation) . "\n\n";

        // Only add namespace and use if the generated code doesn't already have them
        if (!str_contains($phpCode, 'namespace ')) {
            $header .= "namespace {$namespace};\n\n"
                . "use HalfBaked\\Pipeline\\BakedStepInterface;\n\n";
        }

        file_put_contents($filePath, $header . $phpCode . "\n");

        // --- VERIFICATION: replay all logs through the generated class ---
        $verifyResult = $this->verifyGenerated($filePath, $fqcn, $logs);

        if ($verifyResult === null) {
            return [
                'success' => false,
                'file' => $filePath,
                'class' => $fqcn,
                'message' => "Generated code failed to load — syntax error or missing dependencies. File kept at {$filePath} for inspection.",
            ];
        }

        return [
            'success' => $verifyResult->isAcceptable(),
            'file' => $filePath,
            'class' => $fqcn,
            'accuracy' => $verifyResult->accuracy,
            'verification' => $verifyResult->report(),
            'message' => $verifyResult->isPerfect()
                ? "Baked '{$step->getName()}' → {$className} — VERIFIED: {$verifyResult->passed}/{$verifyResult->total} examples match perfectly."
                : ($verifyResult->isAcceptable()
                    ? "Baked '{$step->getName()}' → {$className} — {$verifyResult->passed}/{$verifyResult->total} passed (" . round($verifyResult->accuracy * 100) . "%). Review edge cases."
                    : "Baked '{$step->getName()}' → {$className} — FAILED verification: only {$verifyResult->passed}/{$verifyResult->total} passed. File kept for inspection."),
        ];
    }

    /**
     * Load a generated class and verify it against logs.
     */
    private function verifyGenerated(string $filePath, string $fqcn, array $logs): ?VerifyResult
    {
        try {
            require_once $filePath;
        } catch (\Throwable) {
            return null;
        }

        if (!class_exists($fqcn)) {
            return null;
        }

        $instance = new $fqcn();
        if (!$instance instanceof \HalfBaked\Pipeline\BakedStepInterface) {
            return null;
        }

        $verifier = new Verifier();
        return $verifier->verify($instance, $logs);
    }

    private function buildBakingPrompt(Step $step, array $logs, string $className, string $namespace): string
    {
        $prompt = "Analyze these input/output pairs from a pipeline step and write a PHP class that produces the same outputs deterministically.\n\n";

        $prompt .= "## Step: {$step->getName()}\n\n";

        if ($step->getPrompt()) {
            $prompt .= "Original LLM prompt: {$step->getPrompt()}\n\n";
        }

        if ($step->hasInputSchema()) {
            $prompt .= "Input schema: " . json_encode($step->getInputSchema()) . "\n\n";
        }

        if ($step->hasOutputSchema()) {
            $prompt .= "Output schema: " . json_encode($step->getOutputSchema()) . "\n\n";
        }

        // Include up to 20 example pairs
        $examples = array_slice($logs, 0, 20);
        $prompt .= "## Execution Examples (" . count($examples) . " of " . count($logs) . ")\n\n";

        foreach ($examples as $i => $log) {
            $prompt .= "### Example " . ($i + 1) . "\n";
            $prompt .= "Input: " . json_encode($log['input'], JSON_PRETTY_PRINT) . "\n";
            $prompt .= "Output: " . json_encode($log['output'], JSON_PRETTY_PRINT) . "\n\n";
        }

        $prompt .= "## Requirements\n\n";
        $prompt .= "1. Write a PHP class named `{$className}` that implements `BakedStepInterface`\n";
        $prompt .= "2. The class must have a public `execute(array \$input): array` method\n";
        $prompt .= "3. It must produce outputs matching the patterns shown in the examples\n";
        $prompt .= "4. Use deterministic PHP logic — no randomness, no external API calls\n";
        $prompt .= "5. Handle edge cases visible in the examples\n";
        $prompt .= "6. Use `namespace {$namespace};`\n";
        $prompt .= "7. Include `use HalfBaked\\Pipeline\\BakedStepInterface;`\n";
        $prompt .= "8. Do NOT include `<?php` or `declare(strict_types=1)` — those are added automatically\n\n";
        $prompt .= "Return the class code in the `php_code` field, an explanation in `explanation`, and your confidence (0-1) in `confidence`.\n";

        return $prompt;
    }

    private function bakingSystemPrompt(): string
    {
        return "You are a PHP code generator that converts LLM behavior into deterministic PHP classes. "
            . "Study the input/output examples carefully to identify the transformation pattern. "
            . "Write clean, efficient PHP 8.1+ code. Use match expressions, null coalescing, and typed properties. "
            . "If the pattern involves string manipulation, validation, data transformation, or business logic, "
            . "implement it directly. If the pattern is too complex or context-dependent to fully capture in code, "
            . "set confidence below 0.5 and explain what's missing.";
    }

    private function generateClassName(string $stepName): string
    {
        // validate_address → ValidateAddress
        return str_replace(' ', '', ucwords(str_replace(['_', '-', '.'], ' ', $stepName)));
    }

    private function stripCodeFences(string $code): string
    {
        // Remove ```php ... ``` wrapping
        $code = preg_replace('/^```(?:php)?\s*\n?/i', '', $code);
        $code = preg_replace('/\n?```\s*$/', '', $code);
        return trim($code);
    }

    private function countRuns(array $logs): int
    {
        return count($logs);
    }
}
